--Table fields
CREATE TABLE slide
(
    id              INT8 GENERATED BY DEFAULT AS IDENTITY,
    image_Url       VARCHAR(500)   NULL,
    organization_id INT8           NOT NULL,
    "text"          TEXT           NULL,
    order_number    INT            NULL,

-- Timestamp fields
    created_date    timestamptz(0) NOT NULL DEFAULT NOW(),
    created_by      varchar(100)   NULL,
    modified_date   timestamptz(0) NULL,
    modified_by     varchar(100)   NULL,

--Soft delete
    deleted         bool           NOT NULL DEFAULT FALSE,

--Pk & Fk
    CONSTRAINT slide_pk PRIMARY KEY (id),
    CONSTRAINT slide_fk FOREIGN KEY (organization_id) REFERENCES organization (id)
);

